name = "ZuiderSchemer Pack"
author = "Thijzert"
version = "1.0.0+1.21.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df45699ff3e5e3f9e46febb7a7bc0081afd3112d4c572abc71bb4efe18cf50bd"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
